name: Build llama.cpp Snapdragon Android 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/snapdragon-toolchain/arm64-android:v0.7

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: false

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            bc \
            bison \
            flex \
            openssl \
            libssl-dev \
            docker.ce

      - name: Clone llama.cpp
        run: |
          git clone https://github.com/ggml-org/llama.cpp.git

      - name: Build Snapdragon Android
        run: |
          cd llama.cpp
          ./scripts/snapdragon/build.py --target adb

      - name: Package build
        run: |
          cd llama.cpp
          tar -czf ../llama-cpp-snapdragon-android.tar.gz pkg-adb/llama.cpp

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: llama-cpp-snapdragon-android
          path: llama-cpp-snapdragon-android.tar.gz
