name: Build llama.cpp Snapdragon Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            build-essential \
            bc \
            bison \
            flex \
            openssl \
            libssl-dev \
            docker.ce

      - name: Clone llama.cpp
        run: |
          git clone https://github.com/ggml-org/llama.cpp.git

      - name: Build Snapdragon Android
        run: |
          cd llama.cpp
          ./scripts/snapdragon/build.py --target adb
